version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - "8081:8080"
    depends_on:
      - postgres
      - nats
    env_file:
      - .env

  worker:
    build:
      context: .
      dockerfile: Dockerfile-worker
    depends_on:
      - postgres
      - nats
    env_file:
      - .env

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
      POSTGRES_DB: taskqueue
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nats:
    image: nats:2.10
    ports:
      - "4222:4222"
      - "8622:8222"

volumes:
  postgres_data:
